rating_mapping_ = {
    'AAA': {'rtg_normal': 'AAA', 'rnk': 1},
    'AA+': {'rtg_normal': 'AA', 'rnk': 2},
    'AA': {'rtg_normal': 'AA', 'rnk': 3},
    'AA-': {'rtg_normal': 'AA', 'rnk': 4},
    'A+': {'rtg_normal': 'A', 'rnk': 5},
    'A': {'rtg_normal': 'A', 'rnk': 6},
    'A (sf)': {'rtg_normal': 'A', 'rnk': 6},
    'A-': {'rtg_normal': 'A', 'rnk': 7},
    'A- (sf)': {'rtg_normal': 'A', 'rnk': 7},
    'BBB+': {'rtg_normal': 'BBB', 'rnk': 8},
    'BBB+ (sf)': {'rtg_normal': 'BBB', 'rnk': 8},
    'BBB': {'rtg_normal': 'BBB', 'rnk': 9},
    'BBB (sf)': {'rtg_normal': 'BBB', 'rnk': 9},
    'BBB-': {'rtg_normal': 'BBB', 'rnk': 10},
    'BBB- (sf)': {'rtg_normal': 'BBB', 'rnk': 10},
    'BB+': {'rtg_normal': 'BB', 'rnk': 11},
    'BB+ (sf)': {'rtg_normal': 'BB', 'rnk': 11},
    'BB': {'rtg_normal': 'BB', 'rnk': 12},
    'BB (sf)': {'rtg_normal': 'BB', 'rnk': 12},
    'BB-': {'rtg_normal': 'BB', 'rnk': 13},
    'BB- (sf)': {'rtg_normal': 'BB', 'rnk': 13},
    'B+': {'rtg_normal': 'B', 'rnk': 14},
    'B+ (sf)': {'rtg_normal': 'B', 'rnk': 14},
    'B': {'rtg_normal': 'B', 'rnk': 15},
    'B-': {'rtg_normal': 'B', 'rnk': 16},
    'CCC+': {'rtg_normal': 'CCC', 'rnk': 17},
    'CCC': {'rtg_normal': 'CCC', 'rnk': 18},
    'CCC-': {'rtg_normal': 'CCC', 'rnk': 19},
    'CC': {'rtg_normal': 'CC', 'rnk': 20},
    'C': {'rtg_normal': 'C', 'rnk': 21},
    'D': {'rtg_normal': 'D', 'rnk': 22},
    'NR': {'rtg_normal': 'NR', 'rnk': 16.5},
    'NR/NR': {'rtg_normal': 'NR', 'rnk': 16.5},
    'SD': {'rtg_normal': 'NR', 'rnk': 16.5},
}

rating_mapping = {
    'AAA': {'rtg_normal': 'AAA', 'rnk': 1, 'rtg_group': 'AAA'},
    'AA+': {'rtg_normal': 'AA+', 'rnk': 2, 'rtg_group': 'AA'},
    'AA': {'rtg_normal': 'AA', 'rnk': 3, 'rtg_group': 'AA'},
    'AA-': {'rtg_normal': 'AA-', 'rnk': 4, 'rtg_group': 'AA'},
    'A+': {'rtg_normal': 'A+', 'rnk': 5, 'rtg_group': 'A'},
    'A': {'rtg_normal': 'A', 'rnk': 6, 'rtg_group': 'A'},
    'A (sf)': {'rtg_normal': 'A', 'rnk': 6, 'rtg_group': 'A'},
    'A-': {'rtg_normal': 'A-', 'rnk': 7, 'rtg_group': 'A'},
    'A- (sf)': {'rtg_normal': 'A-', 'rnk': 7, 'rtg_group': 'A'},
    'BBB+': {'rtg_normal': 'BBB+', 'rnk': 8, 'rtg_group': 'BBB'},
    'BBB+ (sf)': {'rtg_normal': 'BBB+', 'rnk': 8, 'rtg_group': 'BBB'},
    'BBB': {'rtg_normal': 'BBB', 'rnk': 9, 'rtg_group': 'BBB'},
    'BBB (sf)': {'rtg_normal': 'BBB', 'rnk': 9, 'rtg_group': 'BBB'},
    'BBB-': {'rtg_normal': 'BBB-', 'rnk': 10, 'rtg_group': 'BBB'},
    'BBB- (sf)': {'rtg_normal': 'BBB-', 'rnk': 10, 'rtg_group': 'BBB'},
    'BB+': {'rtg_normal': 'BB+', 'rnk': 11, 'rtg_group': 'BB'},
    'BB+ (sf)': {'rtg_normal': 'BB+', 'rnk': 11, 'rtg_group': 'BB'},
    'BB': {'rtg_normal': 'BB', 'rnk': 12, 'rtg_group': 'BB'},
    'BB (sf)': {'rtg_normal': 'BB', 'rnk': 12, 'rtg_group': 'BB'},
    'BB-': {'rtg_normal': 'BB-', 'rnk': 13, 'rtg_group': 'BB'},
    'BB- (sf)': {'rtg_normal': 'BB-', 'rnk': 13, 'rtg_group': 'BB'},
    'B+': {'rtg_normal': 'B+', 'rnk': 14, 'rtg_group': 'B'},
    'B+ (sf)': {'rtg_normal': 'B+', 'rnk': 14, 'rtg_group': 'B'},
    'B': {'rtg_normal': 'B', 'rnk': 15, 'rtg_group': 'B'},
    'B-': {'rtg_normal': 'B-', 'rnk': 16, 'rtg_group': 'B'},
    'CCC+': {'rtg_normal': 'CCC+', 'rnk': 17, 'rtg_group': 'CCC'},
    'CCC': {'rtg_normal': 'CCC', 'rnk': 18, 'rtg_group': 'CCC'},
    'CCC-': {'rtg_normal': 'CCC-', 'rnk': 19, 'rtg_group': 'CCC'},
    'CC': {'rtg_normal': 'CC', 'rnk': 20, 'rtg_group': 'CC'},
    'C': {'rtg_normal': 'C', 'rnk': 21, 'rtg_group': 'C'},
    'D': {'rtg_normal': 'D', 'rnk': 22, 'rtg_group': 'D'},
    'NR': {'rtg_normal': 'NR', 'rnk': 16.5, 'rtg_group': 'NR'},
    'NR/NR': {'rtg_normal': 'NR', 'rnk': 16.5, 'rtg_group': 'NR'},
    'SD': {'rtg_normal': 'NR', 'rnk': 16.5, 'rtg_group': 'NR'},
}
